import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html  lang="en">
      <body className={inter.className}>
        <Link href='/'>Main</Link>
        <Link href='/users'>Users</Link>
        <h1 className='bg-[lightblue] text-white'>THIS IS THE TEXT</h1>
        <div className="p-3">{children}</div>
  

    
      
 
      </body>

    </html>
  )
}
